formatted by prettier
annmiro/chess-club pull request #1
Opened 2024-03-02 16:26 UTC by annmiro

2024-03-02 17:34 UTC, demidemid requested changes

2024-03-02 17:34 UTC, demidemid commented on styles/mixins/title.css
> +  margin-top: 0;
тут не должно быть стилей отвечающих за позиционирование, добавляя этот класс-миксин ты должна только менять визуальное офрмление

2024-03-02 17:34 UTC, demidemid commented on index.html
> +              class="project-info__image"
забыла добавить width и height

2024-03-02 17:34 UTC, demidemid commented on styles/blocks/comment.css
> +  font-size: 18px;
переопределяешь 18 на 18

2024-03-02 17:34 UTC, demidemid commented on styles/blocks/comment.css
> +  font-size: 18px;
этот элемент точно не ссылка по макету?

2024-03-02 17:34 UTC, demidemid commented on styles/blocks/project-business-plan.css
> +  background-size: cover;
нужен фон цветовой по умолчанию, у меня кратинки не подгрузились и все выглядит не очень

<img width="374" alt="image" src="https://github.com/annmiro/chess-club/assets/24936371/c8932ea8-28d1-4dd1-b53c-cadea5ab547a">

2024-03-02 17:34 UTC, demidemid commented on styles/blocks/button.css
> +  width: 114px;
нельзя ограничивать кнопку по ширине тут, если текст будет длиннее она будет вот такой

<img width="374" alt="image" src="https://github.com/annmiro/chess-club/assets/24936371/7d14ef9b-8d5f-415f-b638-9b26cb864fa8">

должно быть min-width, а не width

2024-03-02 21:03 UTC, annmiro commented on styles/blocks/comment.css
> +  font-size: 18px;
как это определить? по макету я не вижу ссылок

2024-03-02 21:08 UTC, annmiro commented on styles/blocks/project-business-plan.css
> +  background-size: cover;
добавила

2024-03-02 21:09 UTC, annmiro commented on styles/blocks/button.css
> +  width: 114px;
ok

2024-03-02 21:17 UTC, annmiro commented on styles/mixins/title.css
> +  margin-top: 0;
скорректировано

2024-03-02 21:21 UTC, annmiro commented on index.html
> +              class="project-info__image"
добавлены

2024-03-03 10:53 UTC, demidemid approved these changes

2024-03-03 12:34 UTC, merged